config/routes.rb
require 'sidekiq/web'
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  resources :events,      only: %i[index show edit update new create destroy]
  resources :roles,       only: %i[new create edit update destroy]
  resources :profiles,    only: %i[new create show edit update destroy]
  resources :tours,       only: %i[new create show edit update destroy]
  resources :venues,      only: %i[new create edit update destroy]
  resources :event_types, only: %i[new create edit update destroy]
  resources :role_types,  only: %i[new create edit update destroy]
  resources :role_departments,  only: %i[new create destroy]
  resources :event_departments, only: %i[new create destroy]
  resources :users,             only: %i[edit update destroy]
  resources :logs,              only: %i[index]

  post '/search',           to: 'searches#global',   as: :search_global
  post '/role-type-lookup', to: 'role_types#lookup', as: :role_types_lookup
  post '/profile-lookup',   to: 'profiles#lookup',   as: :profiles_lookup
  post '/venue-lookup',     to: 'venues#lookup',     as: :venues_lookup
  post '/event-lookup',     to: 'events#lookup',     as: :events_lookup
  post '/town-lookup',      to: 'towns#lookup',      as: :towns_lookup

  get '/events/:id/clone',  to: 'events#clone',      as: :clone_event
  post '/events/:id/clone', to: 'events#duplicate',  as: :duplicate_event

  get   '/profiles/:id/add-job', to: 'profiles#add_role', as: :profiles_add_role
  post  '/profiles/:id/add-job', to: 'profiles#create_role',
                                 as: :profiles_create_role
  get  '/profiles/:id/claim',   to: 'profiles#claim',    as: :profiles_claim
  post '/profiles/:id/claim',   to: 'profiles#register_claim',
                                as: :profiles_register_claim

  get '/admin',             to: 'admin#index',       as: :admin_index
  get '/admin/events',      to: 'admin#events',      as: :admin_events
  get '/admin/venues',      to: 'admin#venues',      as: :admin_venues
  get '/admin/venues-map',  to: 'admin#venues_map',  as: :admin_venues_map
  get '/admin/profiles',    to: 'admin#profiles',    as: :admin_profiles
  get '/admin/tours',       to: 'admin#tours',       as: :admin_tours
  get '/admin/event_types', to: 'admin#event_types', as: :admin_event_types
  get '/admin/users',       to: 'admin#users',       as: :admin_users
  get '/admin/roles',       to: 'admin#roles',       as: :admin_roles
  get '/admin/role_types',  to: 'admin#role_types',  as: :admin_role_types
  get '/admin/role_departments',  to: 'admin#role_departments',
                                  as: :admin_role_departments
  get '/admin/event_departments', to: 'admin#event_departments',
                                  as: :admin_event_departments

  get '/about',   to: 'pages#about',   as: :pages_about
  get '/terms',   to: 'pages#terms',   as: :pages_terms
  get '/privacy', to: 'pages#privacy', as: :pages_privacy
  get '/sitemap.xml', to: 'pages#sitemap', as: :pages_sitemap

  get '/:username', to: 'profiles#home', as: :profile_home
  get '/venues/:id/:slug', to: 'venues#show', as: :venues_show
  get '/events/:id/:slug', to: 'events#show', as: :events_home
end
# rubocop:enable Metrics/BlockLength

app/views/admin/_sort_link.html.haml
- if @sort_by == key
  - dir = @sort_direction == 'desc' ? 'asc' : 'desc'
  - klass = 'sorted-by'
- else
  - dir = 'asc'
  - klass = ''

= link_to title, "?sort-by=#{key}&sort-direction=#{dir}", class: "#{klass} #{dir}"

app/views/admin/departments.html.haml
- content_for :page_title do
  Admin role departments

.panel
  .panel-head
    Role departments
    = link_to 'New', new_role_department_path, class: 'pull-right'
  .panel-body
    .table.list
      - @departments.each do |department|
        - present department do |department|
          .tr
            .td
              = department.id
            .td
              = department.name
            .td{class: department.role_types.count.zero? ? 'grey' : ''}
              = department.role_types.count
              role types
            .td.text-right{title: 'Created'}
              = department.created_date
            .td.text-right
              = link_to 'Delete', role_department_path(department), title: 'delete', method: 'DELETE', class: 'danger confirm'
    = paginate @departments

app/views/admin/event_departments.html.haml
- content_for :page_title do
  Admin Event departments

.panel
  .panel-head
    Event departments
    = link_to 'New', new_event_department_path, class: 'pull-right'
  .panel-body
    .table.list
      - @departments.each do |department|
        - present department do |department|
          .tr
            .td
              = department.id
            .td
              = department.name
            .td{class: department.event_types.count.zero? ? 'grey' : ''}
              = department.event_types.count
              event types
            .td.text-right{title: 'Created'}
              = department.created_date
            .td.text-right
              = link_to 'Delete', event_department_path(department), title: 'delete', method: 'DELETE', class: 'danger confirm'
    = paginate @departments

app/views/admin/event_types.html.haml
- content_for :page_title do
  Admin role types


- @departments.each do |department|
  .panel
    .panel-head
      = department.name
      = link_to 'New', new_event_type_path(event_department_id: department.id), class: 'pull-right'
    .panel-body
      .table.list
        - department.event_types.each do |event_type|
          - present event_type do |event_type|
            .tr
              .td
                = link_to 'Edit', edit_event_type_path(event_type)
              .td
                = link_to event_type.title, admin_events_path(type_id: event_type)
              .td{class: event_type.events.count.zero? ? 'grey' : ''}
                = "#{event_type.events.count} #{'event'.pluralize(event_type.events.count)}"
              .td.text-right
                = event_type.created_date
              .td.text-right
                = link_to 'Delete', event_type_path(event_type), title: 'delete', method: 'DELETE', class: 'danger confirm'

app/views/admin/events.html.haml
- content_for :page_title do
  Admin events

.panel
  .panel-head
    - if @type.present?
      = "#{@type.title} Events"
    - else
      Events
    = link_to 'New', new_event_path, class: 'pull-right'
  .panel-body
    .table.list
      - @events.each do |event|
        - present event do |event|
          .tr{valign: 'top'}
            .td
              = link_to 'Edit', edit_event_path(event)
            .td
              = link_to event.name.truncate(30), events_home_path(id: event, slug: event.slug)

            .td
              = event.venue.name

            .td{title: 'when this event is happening'}
              = event.date_str_sml

            .td{class: event.roles.count.zero? ? 'grey' : ''}
              = "#{event.roles.count} #{'role'.pluralize(event.roles.count)}"

            .td{title: event.user.email}
              = event.user.name
              .grey
                = event.created_date
            .td
              = link_to 'Delete', event_path(event), title: 'delete', method: 'DELETE', class: 'danger confirm'
    = paginate @events

app/views/admin/index.html.haml
- content_for :page_title do
  Admin index

.panel
  .panel-head
    Records
  .panel-body
    .table.list
      .tr
        .td
          = @profiles.count
        .td
          = link_to 'Profiles', admin_profiles_path
        .td
          Most Recent:
          - if @profiles.any?
            - present @profiles.last do |profile|
              = profile.created_date
      .tr
        .td
          = @roles.count
        .td
          = link_to 'Roles', admin_roles_path
        .td
          Most Recent:
          - if @roles.any?
            - present @roles.last do |role|
              = role.created_date
      .tr
        .td
          = @events.count
        .td
          = link_to 'Events', admin_events_path
        .td
          Most Recent:
          - present @events.last do |event|
            = event.created_date
      .tr
        .td
          = @tours.count
        .td
          = link_to 'Tours', admin_tours_path
        .td
          Most Recent:
          - present @tours.last do |tour|
            = tour.created_date
      .tr
        .td
          = @venues.count
        .td
          = link_to 'Venues', admin_venues_path
        .td
          Most Recent:
          - present @venues.last do |venue|
            = venue.created_date
      .tr
        .td
          = @users.count
        .td
          = link_to 'Users', admin_users_path
        .td
          Most Recent:
          - present @users.last do |user|
            = user.created_date

app/views/admin/profiles.html.haml
- content_for :page_title do
  Admin profiles

.panel
  .panel-head
    = "Profiles (#{@profiles.total_count})"
  .panel-body
    .table.list
      - @profiles.each do |profile|
        - present profile do |profile|
          .tr
            .td
              = profile.id
            .td
              = link_to 'Edit', edit_profile_path(profile)
            .td
              = link_to profile.title, profile_home_path(username: profile.username)

            .td{class: profile.roles.count.zero? ? 'grey' : ''}
              = "#{profile.roles.count} #{'role'.pluralize(profile.roles.count)}"

            .td{class: profile.events.count.zero? ? 'grey' : ''}
              = "#{profile.events.count} #{'event'.pluralize(profile.events.count)}"
            .td
              = profile.yes_or_no(:verified)
            .td
              - if profile.unowned?
                .bool.no claimed
              - else
                .bool.yes claimed
            .td{title: 'Created'}
              = profile.created_date
            .td
              = link_to 'Delete', profile_path(profile), class: 'danger confirm', title: 'Delete this profile', method: 'DELETE'
  = paginate @profiles

app/views/admin/role_departments.html.haml
- content_for :page_title do
  Admin role departments

.panel
  .panel-head
    Role departments
    = link_to 'New', new_role_department_path, class: 'pull-right'
  .panel-body
    .table.list
      - @departments.each do |department|
        - present department do |department|
          .tr
            .td
              = department.id
            .td
              = department.name
            .td{class: department.role_types.count.zero? ? 'grey' : ''}
              = department.role_types.count
              role types
            .td.text-right{title: 'Created'}
              = department.created_date
            .td.text-right
              = link_to 'Delete', role_department_path(department), title: 'delete', method: 'DELETE', class: 'danger confirm'
    = paginate @departments

app/views/admin/role_types.html.haml
- content_for :page_title do
  Admin role types


- @departments.each do |department|
  .panel
    .panel-head
      = department.name
      = link_to 'New', new_role_type_path(role_department_id: department.id), class: 'pull-right'
    .panel-body
      .table.list
        - department.role_types.each do |role_type|
          - present role_type do |role_type|
            .tr
              .td
                = link_to 'Edit', edit_role_type_path(role_type)
              .td
                = role_type.name
              .td{class: role_type.roles.count.zero? ? 'grey' : ''}
                = "#{role_type.roles.count} #{'role'.pluralize(role_type.roles.count)}"
              .td.text-right
                = role_type.created_date
              .td.text-right
                = link_to 'Delete', role_type_path(role_type), title: 'delete', method: 'DELETE', class: 'danger confirm'

app/views/admin/roles.html.haml
- content_for :page_title do
  Admin roles

.panel
  .panel-head
    Roles
  .panel-body
    .table.list
      - @roles.each do |role|
        - present role do |role|
          .tr
            .td
              = role.id
            .td
              = link_to 'Edit', edit_role_path(role)
            .td
              = link_to role.profile.title, profile_home_path(username: role.profile.username)
            .td
              = role.event_role? ? 'E' : 'T'
            .td
              - if role.event_role?
                = link_to role.event.name, events_home_path(id: role.event, slug: role.event.slug)
              - else
                = link_to role.tour.name, tour_path(role.tour)
            .td
              = role.role_type.name
            .td
              = role.role_type.role_department.name
            .td
              = role.created_date
            .td
              = link_to 'Delete', role_path(role), class: 'danger confirm', title: 'Delete this role', method: 'DELETE'
    = paginate @roles

app/views/admin/tours.html.haml
- content_for :page_title do
  Admin tours

.panel
  .panel-head
    Tours
    = link_to 'New', new_tour_path, class: 'pull-right'
  .panel-body
    .table.list
      - @tours.each do |tour|
        - present tour do |tour|
          .tr{valign: 'top'}
            .td
              = link_to 'Edit', edit_tour_path(tour)
            .td
              = link_to tour.title, tour_path(tour)
            .td
              = tour.events.count
              events
            .td
              = tour.roles.count
              tour roles
            .td.text-right
              = tour.yes_or_no(:verified)
            .td{title: tour.user.email}
              = tour.user.name
              .grey
                = tour.created_date
            .td
              = link_to 'Delete', tour_path(tour), class: 'danger confirm', title: 'Delete this tour', method: 'DELETE'
    = paginate @tours

app/views/admin/users.html.haml
- content_for :page_title do
  Admin users

.panel
  .panel-head
    Users
  .panel-body
    .table.list
      .thead
        .tr
          .td
            = render 'sort_link', title: 'Email', key: 'email'
          .td
            = render 'sort_link', title: 'Profile', key: 'profiles.name'
          .td
            = render 'sort_link', title: 'Last seen', key: 'last_seen'
          .td
            Logs
          .td
          .td
      - @users.each do |user|
        - present user do |user|
          .tr{valign: 'top'}
            .td.mobile-title{class: user.banned? ? 'danger' : ''}
              = user.email
            .td.mobile-50
              - if user.profile.nil?
                none
              - else
                = link_to user.profile.title, profile_home_path(username: user.profile.username)
            .td.mobile-50.mobile-text-right
              = user.formatted_time_sml(:last_seen)
            .td.mobile-30
              = user.logs.count
              ev
            .td.mobile-30.text-center
              = link_to 'Edit', edit_user_path(user)
            .td.mobile-30.text-right
              - unless user.banned?
                = link_to 'Ban', user_path(user), method: 'DELETE', class: 'confirm danger', title: 'Ban this user'
    = paginate @users

app/views/admin/venues.html.haml
- content_for :page_title do
  Admin venues

.panel
  .panel-head
    = "Venues (#{@venues.total_count})"
    = link_to 'New', new_venue_path, class: 'edit-link'
    = link_to 'Map', admin_venues_map_path, class: 'edit-link'
  .panel-body
    .table.list
      - @venues.each do |venue|
        - present venue do |venue|
          .tr
            .td
              = link_to 'Edit', edit_venue_path(venue)
            .td
              = link_to venue.title, venues_show_path(venue, venue.slug)
            .td
              = "#{venue.town.title}, #{venue.town.country_iso}"
            .td
              = venue.created_date
            .td.text-right
              = venue.events.count
              Events
    = paginate @venues

app/views/admin/venues_map.html.haml
- content_for :page_title do
  Admin venues map

%script{:type=>"text/javascript"}
  var map_locations = [
  - @venues.each do |venue|
    = raw "[#{venue.latitude},#{venue.longitude},\"#{venue.name}\",\"#{venues_show_path(venue, venue.slug)}\"],"
  ]

.panel
  .panel-head
    = "Venues (#{@venues.count})"
  #venue_map.large-map