config/routes.rb
require 'sidekiq/web'
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  resources :events,      only: %i[index show edit update new create destroy]
  resources :roles,       only: %i[new create edit update destroy]
  resources :profiles,    only: %i[new create show edit update destroy]
  resources :tours,       only: %i[new create show edit update destroy]
  resources :venues,      only: %i[new create edit update destroy]
  resources :event_types, only: %i[new create edit update destroy]
  resources :role_types,  only: %i[new create edit update destroy]
  resources :role_departments,  only: %i[new create destroy]
  resources :event_departments, only: %i[new create destroy]
  resources :users,             only: %i[edit update destroy]
  resources :logs,              only: %i[index]

  post '/search',           to: 'searches#global',   as: :search_global
  post '/role-type-lookup', to: 'role_types#lookup', as: :role_types_lookup
  post '/profile-lookup',   to: 'profiles#lookup',   as: :profiles_lookup
  post '/venue-lookup',     to: 'venues#lookup',     as: :venues_lookup
  post '/event-lookup',     to: 'events#lookup',     as: :events_lookup
  post '/town-lookup',      to: 'towns#lookup',      as: :towns_lookup

  get '/events/:id/clone',  to: 'events#clone',      as: :clone_event
  post '/events/:id/clone', to: 'events#duplicate',  as: :duplicate_event

  get   '/profiles/:id/add-job', to: 'profiles#add_role', as: :profiles_add_role
  post  '/profiles/:id/add-job', to: 'profiles#create_role',
                                 as: :profiles_create_role
  get  '/profiles/:id/claim',   to: 'profiles#claim',    as: :profiles_claim
  post '/profiles/:id/claim',   to: 'profiles#register_claim',
                                as: :profiles_register_claim

  get '/admin',             to: 'admin#index',       as: :admin_index
  get '/admin/events',      to: 'admin#events',      as: :admin_events
  get '/admin/venues',      to: 'admin#venues',      as: :admin_venues
  get '/admin/venues-map',  to: 'admin#venues_map',  as: :admin_venues_map
  get '/admin/profiles',    to: 'admin#profiles',    as: :admin_profiles
  get '/admin/tours',       to: 'admin#tours',       as: :admin_tours
  get '/admin/event_types', to: 'admin#event_types', as: :admin_event_types
  get '/admin/users',       to: 'admin#users',       as: :admin_users
  get '/admin/roles',       to: 'admin#roles',       as: :admin_roles
  get '/admin/role_types',  to: 'admin#role_types',  as: :admin_role_types
  get '/admin/role_departments',  to: 'admin#role_departments',
                                  as: :admin_role_departments
  get '/admin/event_departments', to: 'admin#event_departments',
                                  as: :admin_event_departments

  get '/about',   to: 'pages#about',   as: :pages_about
  get '/terms',   to: 'pages#terms',   as: :pages_terms
  get '/privacy', to: 'pages#privacy', as: :pages_privacy
  get '/sitemap.xml', to: 'pages#sitemap', as: :pages_sitemap

  get '/:username', to: 'profiles#home', as: :profile_home
  get '/venues/:id/:slug', to: 'venues#show', as: :venues_show
  get '/events/:id/:slug', to: 'events#show', as: :events_home
end
# rubocop:enable Metrics/BlockLength

app/models/event.rb
class Event < ApplicationRecord
  include PgSearch
  include Events::Mixins
  extend Events::Scopes
  default_scope { where(deleted_at: [nil]) }

  belongs_to :event_type
  belongs_to :venue
  belongs_to :tour, optional: true
  belongs_to :user
  has_many :roles
  has_many :logs, as: :record

  validates :name, presence: true

  delegate :town, :latitude, :longitude, :has_coords?, to: :venue

  attr_accessor :lookup_query, :venue_name, :venue_address, :town_name, :town_id

  alias type event_type

  pg_search_scope :fuzzy_matches,
                  against: %i[name description],
                  using: { tsearch: { any_word: true } }
end

# == Schema Information
#
# Table name: events
#
#  id            :bigint(8)        not null, primary key
#  name          :text
#  date          :date
#  event_type_id :bigint(8)
#  venue_id      :bigint(8)
#  tour_id       :bigint(8)
#  user_id       :bigint(8)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  description   :text
#  verified      :boolean
#  deleted_at    :date
#

app/models/event_type.rb
class EventType < ApplicationRecord
  include EventTypes::Mixins
  default_scope { where(deleted_at: [nil]) }

  belongs_to :event_department, optional: true

  has_many :events
  has_many :logs, as: :record

  validates :name, presence: true

  alias department event_department

  def title
    name.titleize
  end
end

# == Schema Information
#
# Table name: event_types
#
#  id                  :bigint(8)        not null, primary key
#  name                :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  deleted_at          :date
#  event_department_id :bigint(8)
#  description         :text
#

app/models/events/mixins.rb
module Events
  module Mixins
    def delete
      roles.update_all deleted_at: Time.zone.now
      self.deleted_at = Time.zone.now
      save!
    end

    def undelete
      roles_inc_deleted.update_all deleted_at: nil
      self.deleted_at = nil
      save!
    end

    def roles_inc_deleted
      roles.unscoped.all
    end

    def title
      name.titleize
    end

    def venue_title
      venue.title
    end

    def town_title
      town.title
    end

    def full_title
      "#{name.titleize}, #{venue_title}, #{town_title} - \
      #{date_str}"
    end

    def date_str
      date.strftime('%d %B %Y')
    end

    def date_str_sml
      date.strftime('%d-%m-%y')
    end

    def on_tour?
      tour_id.present?
    end

    def tour_roles
      return [] if tour.nil?
      tour.roles
    end

    def owner?(user)
      user_id.present? && (user&.id == user_id)
    end

    def slug
      "#{name}-#{venue.name}-#{venue.town_title}".parameterize
    end
  end
end

app/models/events/scopes.rb
module Events
  module Scopes
    def deleted
      unscoped.where.not(deleted_at: [nil])
    end

    def recent(limit = 15)
      where('date < ?', Time.zone.tomorrow)
        .reorder('date desc')
        .limit(limit)
    end
  end
end

app/controllers/admin/event_types.rb
module Admin
  class EventTypes < ::AdminControllerAction
    def call
      expose(event_types, '@event_types')
    end

    private

    def event_types
      @event_types ||= EventType.order(:name).page(params[:page])
    end
  end
end

app/controllers/admin/events.rb
module Admin
  class Events < ::AdminControllerAction
    def call
      expose(events, '@events')
      expose(type, '@type')
    end

    private

    def events
      events_by_type || all_events
    end

    def all_events
      @all_events ||= Event.order(id: :desc).page(params[:page])
    end

    def events_by_type
      return if type.nil?
      @event_by_type ||=
        Event.where(event_type: type.id)
             .order(id: :desc)
             .page(params[:page])
    end

    def type
      @type ||= EventType.find(type_id) if type_id.present?
    end

    def type_id
      @type_id ||= params[:type_id]
    end
  end
end

app/controllers/events/clone.rb
module Events
  class Clone < ::EditControllerAction
    def call
      return if controller.performed?
      expose(event, '@event')
      expose(old_event, '@old_event')
    end

    private

    def event
      @event ||= old_event.dup
    end

    def old_event
      @old_event ||= Event.find params[:id]
    end
  end
end

app/controllers/events/create.rb
module Events
  class Create < ::EditControllerAction
    def call
      return render_form if event.errors.any?
      redirect
    end

    private

    def redirect
      # return redirect_to(controller.tour_path(event.tour)) if event.on_tour?
      redirect_to(controller.events_home_path(id: event, slug: event.slug))
    end

    def render_form
      expose(event, '@event')
      expose(departments, '@departments')
      render 'new'
    end

    def safe_params
      @safe_params ||= params.require('event').permit(
        :name, :description, :event_type_id, :venue_id,
        :venue_name, :venue_address, :town_id, :tour_id, :date
      )
    end

    def event
      @event ||= ::Events::Creator.new(safe_params, current_user).call
    end

    def departments
      @departments ||= EventDepartment.all.order(:name)
    end
  end
end

app/controllers/events/destroy.rb
module Events
  class Destroy < ::AdminControllerAction
    def call
      event.delete
      redirect
    end

    private

    def redirect
      redirect_to(
        controller.admin_events_path,
        notice: 'The event has been deleted'
      )
    end

    def event
      @event ||= Event.find params[:id]
    end
  end
end

app/controllers/events/duplicate.rb
module Events
  class Duplicate < ::EditControllerAction
    def call
      return if controller.performed?
      return success if cloner.call
      error
    end

    private

    def success
      redirect_to(
        controller.events_home_path(id: cloner.event, slug: cloner.event.slug),
        notice: 'Event cloned'
      )
    end

    def error
      redirect_to(
        controller.event_path(id: params[:id]),
        alert: cloner.event.errors.full_messages.to_sentence
      )
    end

    def cloner
      @cloner ||= ::Events::Cloner.new(old_event, safe_params, current_user)
    end

    def safe_params
      @safe_params ||= params.require('event').permit(
        :venue_id, :date
      )
    end

    def old_event
      @old_event ||= Event.find params[:id]
    end
  end
end

app/controllers/events/edit.rb
module Events
  class Edit < ::EditControllerAction
    def call
      return if controller.performed?
      return redirect unless user_can_edit_this?
      expose(event, '@event')
    end

    private

    def redirect
      redirect_to(controller.root_path, notice: "You can't do that man.")
    end

    def event
      @event ||= Event.find params[:id]
    end

    def user_can_edit_this?
      current_user.admin? || event.owner?(current_user)
    end
  end
end

app/controllers/events/index.rb
module Events
  class Index < ::ControllerAction
    def call
      expose(recently_added_events, '@recently_added_events')
    end

    private

    def recently_added_events
      @recently_added_events ||= Event.order(id: :desc).limit(10)
    end
  end
end

app/controllers/events/lookup.rb
module Events
  class Lookup < ::ControllerAction
    def call
      expose(events, '@events')
    end

    private

    def events
      @events ||=
        Event.where(venue_id: venue_id, date: date)
    end

    def venue_id
      @venue_id ||= params[:venue_id]
    end

    def date
      @date ||= params[:date]
    end
  end
end

app/controllers/events/new.rb
module Events
  class New < ::EditControllerAction
    def call
      expose(event, '@event')
      expose(tour, '@tour')
      expose(venue, '@venue')
      expose(departments, '@departments')
    end

    private

    def event
      @event ||= Event.new(
        tour_id: tour&.id,
        venue_id: venue&.id,
        name: tour&.name,
        event_type: tour&.tour_type
      )
    end

    def tour
      return if params[:tour_id].nil?
      @tour ||= Tour.find(params[:tour_id])
    end

    def venue
      return if params[:venue_id].nil?
      @venue ||= Venue.find(params[:venue_id])
    end

    def departments
      @departments ||= EventDepartment.all.order(:name)
    end
  end
end

app/controllers/events/show.rb
module Events
  class Show < ::ControllerAction
    def call
      expose(event, '@event')
    end

    private

    def event
      @event ||= Event.find params[:id]
    end
  end
end

app/controllers/events/update.rb
module Events
  class Update < ::EditControllerAction
    def call
      return if controller.performed?
      return error unless user_can_edit_this?
      return error unless event.update(safe_params)
      logger.call
      redirect
    end

    private

    def user_can_edit_this?
      current_user.admin? || event.owner?(current_user)
    end

    def redirect
      redirect_to(
        controller.events_home_path(id: event, slug: event.slug),
        notice: 'The event has been updated'
      )
    end

    def error
      redirect_to(
        controller.events_home_path(id: event, slug: event.slug),
        notice: 'Something went wrong.'
      )
    end

    def safe_params
      @safe_params ||= params.require('event').permit(
        :name, :description, :event_type_id, :venue_id, :venue_name,
        :venue_address, :town_id, :date
      )
    end

    def event
      @event ||= Event.find params.fetch(:id)
    end

    def logger
      @logger ||= ::Utilities::Logger.new(event, 'edited', current_user)
    end
  end
end

app/controllers/events_controller.rb
# handles requests for events routes
class EventsController < ApplicationController
  def index
    ::Events::Index.new(
      self, params
    ).call
  end

  def show
    ::Events::Show.new(
      self, params
    ).call
  end

  def edit
    ::Events::Edit.new(
      self, params
    ).call
  end

  def new
    ::Events::New.new(
      self, params
    ).call
  end

  def create
    ::Events::Create.new(
      self, params
    ).call
  end

  def update
    ::Events::Update.new(
      self, params
    ).call
  end

  def destroy
    ::Events::Destroy.new(
      self, params
    ).call
  end

  def lookup
    ::Events::Lookup.new(
      self, params
    ).call
  end

  def clone
    ::Events::Clone.new(
      self, params
    ).call
  end

  def duplicate
    ::Events::Duplicate.new(
      self, params
    ).call
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_list.html.haml
.table.list
  - events.each do |event|
    - present event do |event|
      .tr
        .td.mobile-title
          = link_to event.title, events_home_path(id: event, slug: event.slug)
        -# don't show venue info if we're on a venue page
        - unless defined? venue
          .td
            = link_to event.venue_title, venues_show_path(event.venue, event.venue.slug)
          .td.mobile-30
            = event.venue.town_title
        .td.mobile-30
          = event.date_str
        .td.text-right.mobile-30
          = "#{event.roles.count} crew"

app/views/events/_event_lookup_list.html.haml
- event = events.first
%h2 Existing events
%label.event_lookup
  = "Existing events at #{event.venue.title} on the #{event.date_str}"
.existing-events
  .event_lookup_list
    %ul
      - events.each do |event|
        - present event do |event|
          %li{'data-id' => event.id}
            %span.lookup-name
              = event.title
            .pull-right
              = '...'
              = "#{event.roles.count} crew"
  .row
    .or
      %span Or

app/views/events/clone.html.haml
- present @event do |event|
  - content_for :page_title do
    = "#{event.full_title} - Edit"

  = simple_form_for(@event, url: duplicate_event_path(@old_event), method: :post) do |f|
    = f.input :venue_id, as: :hidden, input_html: { class: 'venue_lookup_id' }
    .panel
      .panel-head
        Cloning
        = event.name
      .panel-body
        .message
          So this event happened more than once huh? Change the details below
          to the new time and place.
        .row
          = event.description
        .row
          = f.input :lookup_query, as: :string, label: "What's the venue?", |
          required: true, placeholder: 'Search for a venue', input_html: {  value: event&.venue&.title, autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off', class: 'venue_lookup disable-auto-select' }
          .venue_lookup_list
        .row
          = f.input :date, label: 'When is it?'
        .row
          = f.submit 'Clone Event'
        .row
          = link_to 'Cancel', events_home_path(id: @old_event, slug: @old_event.slug)

app/views/events/edit.html.haml
- present @event do |event|
  - content_for :page_title do
    = "#{event.full_title} - Edit"

  = simple_form_for(@event, url: event_path, method: :put) do |f|
    = f.input :venue_id, as: :hidden, input_html: { class: 'venue_lookup_id' }
    .panel
      .panel-head
        Edit event
      .panel-body
        .message
          You're editing a event. It's easy, just fill in this form.
        .row
          = f.input :name, as: :string, label: false, placeholder: 'Event title'
        .row
          = f.input :description, label: false, placeholder: 'Event description'
        .row
          = f.association :event_type, label_method: :title, label: 'What type of event is it?', prompt: 'Select a type of event'
        .row
          = f.input :venue_name, as: :string, label: "What's the venue?", |
          required: true, placeholder: 'Search for a venue', input_html: {value: event&.venue&.title, autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off', class: 'venue_lookup' }
          .venue_lookup_list
        .venue_address.hidden
          .row
            = f.input :venue_address, as: :text, label: 'Venue address', required: false, input_html: { class: 'venue_address' }
          .row
            = f.input :town_name, as: :string, label: 'Town or City', required: false, placeholder: 'Search for a place', input_html: { autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off', class: 'town_lookup' }
            .town_lookup_list
        .row
          = f.input :date, label: 'When is it?'
        .row
          = f.submit 'Update Event'
        .row
          = link_to 'Cancel', events_home_path(id: event, slug: event.slug)
  = render 'logs/log_list', logs: event.logs

app/views/events/lookup.js.erb
$('.event_lookup_list_holder').html(
  <%- if @events.empty? %>
    ""
  <%- else %>
    "<%= escape_javascript(render partial: 'event_lookup_list', locals: { events: @events } ) %>"
  <%- end %>
)
$('.event_lookup_list').show();

app/views/events/new.html.haml
- present @event do |event|
  - content_for :page_title do
    New event

  = simple_form_for(@event, url: events_path, method: :post) do |f|
    = f.input :tour_id, as: :hidden
    = f.input :venue_id, as: :hidden, input_html: { class: 'venue_lookup_id' }
    = f.input :town_id, as: :hidden, input_html: { class: 'town_lookup_id' }
    .panel
      .panel-head
        Add event
      .panel-body
        .message
          - if event.venue.present?
            You're adding an event to
            %em
              = event.venue.title
          - else
            You're adding a new event. It's easy, just fill in this form.
        - if event.errors.any?
          .alert
            = event.errors.full_messages.to_sentence
        .row
          = f.input :name, as: :string, label: 'Event title', placeholder: 'Event title'
        .row
          = f.input :description, label: false, placeholder: 'Event description'
        .row
          = f.input :event_type_id, collection: @departments, as: :grouped_select, group_method: :event_types, label_method: :title, label: 'What type of event is it?', prompt: 'Select a type of event'
        - if event.venue.nil?
          .row
            = f.input :venue_name, as: :string, label: "What's the venue?", |
            required: true, placeholder: 'Search for a venue', input_html: {value: event&.venue&.title, autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off', class: 'venue_lookup' }
            .venue_lookup_list
          .venue_address.hidden
            .row
              = f.input :venue_address, as: :text, label: 'Venue address', required: false, input_html: { class: 'venue_address' }
            .row
              = f.input :town_name, as: :string, label: 'Town or City', required: false, placeholder: 'Search for a place', input_html: { autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off', class: 'town_lookup' }
              .town_lookup_list
        .row
          = f.input :date, label: 'When is it?', end_year: Date.today.year - 20, start_year: Date.today.year + 3, include_blank: false
        .row
          = f.submit 'Add event'

app/views/events/show.html.haml
- present @event do |event|
  - present event.venue do |venue|
    - content_for :page_title do
      = event.full_title

    %script{:type=>"text/javascript"}
      var map_locations = [
      = raw "[#{event.latitude},#{event.longitude},\"#{event.title}\"]"
      ]

    %h1.content-title
      = event.name

    .panel
      .panel-head
        = event.name
        = event.date_str

        - if current_user&.admin? || event.owner?(current_user)
          = link_to 'Edit', edit_event_path(event), class: 'edit-link'
          = link_to 'Clone', clone_event_path(event), class: 'edit-link'
      - if event.has_coords?
        #venue_map.wide-map
      .panel-body
        .table.list
          .tr
            .td
              Venue
            .td
              .div
                = link_to venue.title, venues_show_path(venue, venue.slug)
              .div
                = link_to venue.address, venue.address_url, target: '_blank'
              .div
                = venue.town_full_title
          .tr
            .td
              Date
            .td
              = event.date_str

    - if event.description.present?
      .panel
        .panel-body
          = event.activate_links(simple_format(event.description))

    - if event.roles.any?
      .panel
        .panel-head
          Crew
        .panel-body
          = render 'roles/role_list', roles: event.roles

    .row
      = link_to 'Add crew', new_role_path(event_id: event.id), class: 'button'