config/routes.rb
require 'sidekiq/web'
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  resources :events,      only: %i[index show edit update new create destroy]
  resources :roles,       only: %i[new create edit update destroy]
  resources :profiles,    only: %i[new create show edit update destroy]
  resources :tours,       only: %i[new create show edit update destroy]
  resources :venues,      only: %i[new create edit update destroy]
  resources :event_types, only: %i[new create edit update destroy]
  resources :role_types,  only: %i[new create edit update destroy]
  resources :role_departments,  only: %i[new create destroy]
  resources :event_departments, only: %i[new create destroy]
  resources :users,             only: %i[edit update destroy]
  resources :logs,              only: %i[index]

  post '/search',           to: 'searches#global',   as: :search_global
  post '/role-type-lookup', to: 'role_types#lookup', as: :role_types_lookup
  post '/profile-lookup',   to: 'profiles#lookup',   as: :profiles_lookup
  post '/venue-lookup',     to: 'venues#lookup',     as: :venues_lookup
  post '/event-lookup',     to: 'events#lookup',     as: :events_lookup
  post '/town-lookup',      to: 'towns#lookup',      as: :towns_lookup

  get '/events/:id/clone',  to: 'events#clone',      as: :clone_event
  post '/events/:id/clone', to: 'events#duplicate',  as: :duplicate_event

  get   '/profiles/:id/add-job', to: 'profiles#add_role', as: :profiles_add_role
  post  '/profiles/:id/add-job', to: 'profiles#create_role',
                                 as: :profiles_create_role
  get  '/profiles/:id/claim',   to: 'profiles#claim',    as: :profiles_claim
  post '/profiles/:id/claim',   to: 'profiles#register_claim',
                                as: :profiles_register_claim

  get '/admin',             to: 'admin#index',       as: :admin_index
  get '/admin/events',      to: 'admin#events',      as: :admin_events
  get '/admin/venues',      to: 'admin#venues',      as: :admin_venues
  get '/admin/venues-map',  to: 'admin#venues_map',  as: :admin_venues_map
  get '/admin/profiles',    to: 'admin#profiles',    as: :admin_profiles
  get '/admin/tours',       to: 'admin#tours',       as: :admin_tours
  get '/admin/event_types', to: 'admin#event_types', as: :admin_event_types
  get '/admin/users',       to: 'admin#users',       as: :admin_users
  get '/admin/roles',       to: 'admin#roles',       as: :admin_roles
  get '/admin/role_types',  to: 'admin#role_types',  as: :admin_role_types
  get '/admin/role_departments',  to: 'admin#role_departments',
                                  as: :admin_role_departments
  get '/admin/event_departments', to: 'admin#event_departments',
                                  as: :admin_event_departments

  get '/about',   to: 'pages#about',   as: :pages_about
  get '/terms',   to: 'pages#terms',   as: :pages_terms
  get '/privacy', to: 'pages#privacy', as: :pages_privacy
  get '/sitemap.xml', to: 'pages#sitemap', as: :pages_sitemap

  get '/:username', to: 'profiles#home', as: :profile_home
  get '/venues/:id/:slug', to: 'venues#show', as: :venues_show
  get '/events/:id/:slug', to: 'events#show', as: :events_home
end
# rubocop:enable Metrics/BlockLength

app/models/role.rb
class Role < ApplicationRecord
  include Roles::Mixins
  extend Roles::Scopes
  default_scope { where(deleted_at: [nil]) }

  belongs_to :profile
  belongs_to :event, optional: true
  belongs_to :tour, optional: true
  belongs_to :role_type
  belongs_to :creator, class_name: 'User'
  has_many :logs, as: :record

  delegate :town, :venue, to: :event

  accepts_nested_attributes_for :event

  attr_accessor :profile_name, :role_type_name
end

# == Schema Information
#
# Table name: roles
#
#  id           :bigint(8)        not null, primary key
#  profile_id   :bigint(8)
#  event_id     :bigint(8)
#  role_type_id :bigint(8)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  verified     :boolean
#  creator_id   :integer
#  tour_id      :integer
#  deleted_at   :date
#

app/models/role_type.rb
class RoleType < ApplicationRecord
  extend RoleTypes::Scopes
  include RoleTypes::Mixins
  default_scope { where(deleted_at: [nil]) }

  include PgSearch

  has_many :roles
  belongs_to :role_department
  has_many :logs, as: :record

  pg_search_scope :fuzzy_matches,
                  against: %i[name],
                  using: {
                    tsearch: {
                      any_word: true,
                      dictionary: 'english'
                    }
                  }

  pg_search_scope :matches,
                  against: %i[name],
                  using: {
                    trigram: {
                      threshold: 0.2
                    }
                  }

  def title
    name.titleize
  end

  def department_name
    role_department&.name
  end
end

# == Schema Information
#
# Table name: role_types
#
#  id                 :bigint(8)        not null, primary key
#  name               :text
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  category           :text
#  role_department_id :bigint(8)
#  deleted_at         :date
#

app/models/roles/mixins.rb
module Roles
  module Mixins
    def delete
      self.deleted_at = Time.zone.now
      save!
    end

    def undelete
      self.deleted_at = nil
      save!
    end

    def town
      event&.town
    end

    def venue
      event&.venue
    end

    def coords
      [venue&.latitude, venue.longitude]
    end

    def parent
      return event if event_id.present?
      tour
    end

    def event_role?
      event_id.present?
    end

    def tour_role?
      tour_id.present?
    end

    def venue_title
      venue.title
    end

    def town_title
      town&.title
    end

    def town_and_country_title
      "#{town_title}, #{country_title}"
    end

    def country_title
      town&.country&.title
    end

    def owner?(user)
      profile.user_id.present? && (profile.user_id == user&.id)
    end

    def event_owner?(user)
      event.user_id.present? && (event.user_id == user&.id)
    end

    def can_edit?(user)
      owner?(user) || event_owner?(user)
    end
  end
end

app/models/roles/scopes.rb
module Roles
  module Scopes
    def deleted
      unscoped.where.not(deleted_at: [nil])
    end

    def ordered_by_department
      includes(:role_type)
        .includes(role_type: :role_department)
        .order('role_departments.name, role_types.name')
    end

    def recent(limit = 15)
      where('created_at < ?', Time.zone.tomorrow)
        .reorder('created_at desc')
        .limit(limit)
    end
  end
end

app/controllers/admin/role_types.rb
module Admin
  class RoleTypes < ::AdminControllerAction
    def call
      expose(departments, '@departments')
    end

    private

    def departments
      @departments ||= RoleDepartment.order(:name)
    end
  end
end

app/controllers/admin/roles.rb
module Admin
  class Roles < ::AdminControllerAction
    def call
      expose(roles, '@roles')
    end

    private

    def roles
      @roles ||= Role.order(id: :desc).page(params[:page])
    end
  end
end

app/controllers/roles/create.rb
module Roles
  class Create < ::EditControllerAction
    def call
      return redirect if role.present?
      error
    end

    private

    def redirect
      redirect_to(
        controller.events_home_path(id: role.event, slug: role.event.slug)
      )
    end

    def error
      redirect_to(
        controller.new_role_path(
          event_id: safe_params[:event_id],
          tour_id: safe_params[:tour_id]
        ),
        notice:
          'The name has to be longer than 5 characters and no funny business.'
      )
    end

    def safe_params
      @safe_params ||= params.require('role').permit(
        :event_id, :tour_id, :profile_id, :profile_name, :role_type_id
      )
    end

    def role
      @role ||= ::Roles::Creator.new(safe_params, current_user).call
    end
  end
end

app/controllers/roles/destroy.rb
module Roles
  class Destroy < ::ControllerAction
    def call
      return perms_error unless can_edit?
      role.delete
      logger.call
      redirect
    end

    private

    def redirect
      redirect_to(
        controller.events_home_path(id: role.event, slug: role.event.slug),
        notice: 'The role has been deleted'
      )
    end

    def perms_error
      redirect_to(
        controller.root_path, notice: 'You do not have permission to do this'
      )
    end

    def role
      @roles ||= Role.find(params[:id])
    end

    def can_edit?
      @can_edit ||= current_user.admin? || role.can_edit?(current_user)
    end

    def logger
      @logger ||= ::Utilities::Logger.new(role, 'deleted', current_user)
    end
  end
end

app/controllers/roles/edit.rb
module Roles
  class Edit < ::EditControllerAction
    def call
      return if controller.performed?
      return redirect unless user_can_edit_this?
      expose(role, '@role')
    end

    private

    def redirect
      redirect_to(controller.root_path, notice: "You can't do that man.")
    end

    def role
      @roles ||= Role.unscoped.find params[:id]
    end

    def user_can_edit_this?
      current_user.admin? || role.owner?(current_user)
    end
  end
end

app/controllers/roles/new.rb
module Roles
  class New < ::EditControllerAction
    def call
      expose(role, '@role')
      expose(event, '@event')
      expose(tour, '@tour')
      expose(title, '@title')
    end

    private

    def role
      @roles ||= Role.new(event: event, tour: tour)
    end

    def event
      return if params[:event_id].blank?
      @event ||= Event.find params[:event_id]
    end

    def tour
      return if params[:tour_id].blank?
      @tour ||= Tour.find params[:tour_id]
    end

    def title
      @title ||= event&.full_title || tour&.title
    end
  end
end

app/controllers/roles/update.rb
module Roles
  class Update < ::AdminControllerAction
    def call
      return if controller.performed?
      role.update! safe_params
      logger.call
      redirect
    end

    private

    def redirect
      redirect_to(
        controller.admin_roles_path,
        notice: 'The role has been updated'
      )
    end

    def role
      @roles ||= Role.find params[:id]
    end

    def safe_params
      @safe_params ||= params.require('role').permit(
        :profile_id, :event_id, :creator_id, :verified, :role_type_id
      )
    end

    def logger
      @logger ||=
        ::Utilities::Logger.new(
          role.parent, 'role edited', current_user,
          role.previous_changes.merge(
            role_id: [role.id, role.id]
          )
        )
    end
  end
end

app/controllers/roles_controller.rb
# handles requests for roles routes
class RolesController < ApplicationController
  def edit
    ::Roles::Edit.new(
      self, params
    ).call
  end

  def new
    ::Roles::New.new(
      self, params
    ).call
  end

  def create
    ::Roles::Create.new(
      self, params
    ).call
  end

  def update
    ::Roles::Update.new(
      self, params
    ).call
  end

  def destroy
    ::Roles::Destroy.new(
      self, params
    ).call
  end
end

app/views/roles/_role_list.html.haml
.table.list
  - roles.each do |role|
    .tr
      .td
        = link_to role.profile.title, profile_home_path(username: role.profile.username)
      .td
        = role.role_type.title
      .td.text-right.desktop-only
        = role.role_type.role_department.name
      - if current_user&.admin? || role.can_edit?(current_user)
        .td.text-right
          = link_to 'Delete', role_path(role), class: 'danger confirm', title: 'Delete this role', method: 'DELETE'

app/views/roles/edit.html.haml
- present @role do |role|
  .panel
    .panel-head
      Edit role
      -  if role.deleted_at.present?
        .danger
          THIS ROLE HAS BEEN DELETED
      - elsif current_user&.admin? || role.owner?(current_user)
        .td.text-right
          = link_to 'Delete', role_path(role), class: 'danger confirm edit-link', title: 'Delete this role', method: 'DELETE'
    .panel-body

      = simple_form_for(@role, url: role_path, method: :put) do |f|
        .row
          = f.association :profile, label_method: :title, label: 'Who dat?'
        .row
          = f.association :event, label: 'Where dat?'
        .row
          = f.association :role_type, label: 'What dat?'
        - if current_user.admin?
          .row
            %h5 Admin
          .row
            = f.input :verified, label: 'Verified'
          .row
            = f.association :creator, label: 'Creator'
        .row
          = f.submit 'Update role'

  = render 'logs/log_list', logs: role.logs

app/views/roles/index.html.haml
.panel
  .panel-head
    Recently added events
  .panel-body
    = render 'events/event_list', events: @recently_added_events

app/views/roles/new.html.haml
- present @role do |role|
  - content_for :page_title do
    Add crew to
    = @title

  = simple_form_for(@role, url: roles_path, method: :post) do |f|
    = f.input :event_id, as: :hidden
    = f.input :tour_id, as: :hidden
    = f.input :profile_id, as: :hidden, input_html: { class: 'profile_lookup_id' }
    = f.input :role_type_id, as: :hidden, input_html: { class: 'role_type_lookup_id' }
    .panel.add-role-to-event
      .panel-head
        Add crew
      .panel-body
        .message
          = "You're adding cast or crew to #{@title}."
        .pane
          .row
            = f.input :profile_name, as: :string, label: 'Who was this?', required: true, placeholder: 'Who was this? eg: Alan Smithee', input_html: { autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off', class: 'profile_lookup' }
            .profile_lookup_list
          - if current_user.has_profile?
            .row
              .or
                %span Or
            .row
              = link_to 'It was you', '#', { class: 'button my-profile', 'data-name' => current_user.profile.title, 'data-id' => current_user.profile.id }
        .pane
          .row
            = f.input :role_type_name, as: :string, label: 'What did they do?', required: true, placeholder: 'What did they do? eg: Sound engineer', input_html: { autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off', class: 'role_type_lookup' }
            .role_type_lookup_list
        .row.submit-row
          = f.submit 'Add Crew'
        .row
          = link_to 'Cancel', events_home_path(id: role.event, slug: role.event.slug)