config/routes.rb
require 'sidekiq/web'
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  resources :events,      only: %i[index show edit update new create destroy]
  resources :roles,       only: %i[new create edit update destroy]
  resources :profiles,    only: %i[new create show edit update destroy]
  resources :tours,       only: %i[new create show edit update destroy]
  resources :venues,      only: %i[new create edit update destroy]
  resources :event_types, only: %i[new create edit update destroy]
  resources :role_types,  only: %i[new create edit update destroy]
  resources :role_departments,  only: %i[new create destroy]
  resources :event_departments, only: %i[new create destroy]
  resources :users,             only: %i[edit update destroy]
  resources :logs,              only: %i[index]

  post '/search',           to: 'searches#global',   as: :search_global
  post '/role-type-lookup', to: 'role_types#lookup', as: :role_types_lookup
  post '/profile-lookup',   to: 'profiles#lookup',   as: :profiles_lookup
  post '/venue-lookup',     to: 'venues#lookup',     as: :venues_lookup
  post '/event-lookup',     to: 'events#lookup',     as: :events_lookup
  post '/town-lookup',      to: 'towns#lookup',      as: :towns_lookup

  get '/events/:id/clone',  to: 'events#clone',      as: :clone_event
  post '/events/:id/clone', to: 'events#duplicate',  as: :duplicate_event

  get   '/profiles/:id/add-job', to: 'profiles#add_role', as: :profiles_add_role
  post  '/profiles/:id/add-job', to: 'profiles#create_role',
                                 as: :profiles_create_role
  get  '/profiles/:id/claim',   to: 'profiles#claim',    as: :profiles_claim
  post '/profiles/:id/claim',   to: 'profiles#register_claim',
                                as: :profiles_register_claim

  get '/admin',             to: 'admin#index',       as: :admin_index
  get '/admin/events',      to: 'admin#events',      as: :admin_events
  get '/admin/venues',      to: 'admin#venues',      as: :admin_venues
  get '/admin/venues-map',  to: 'admin#venues_map',  as: :admin_venues_map
  get '/admin/profiles',    to: 'admin#profiles',    as: :admin_profiles
  get '/admin/tours',       to: 'admin#tours',       as: :admin_tours
  get '/admin/event_types', to: 'admin#event_types', as: :admin_event_types
  get '/admin/users',       to: 'admin#users',       as: :admin_users
  get '/admin/roles',       to: 'admin#roles',       as: :admin_roles
  get '/admin/role_types',  to: 'admin#role_types',  as: :admin_role_types
  get '/admin/role_departments',  to: 'admin#role_departments',
                                  as: :admin_role_departments
  get '/admin/event_departments', to: 'admin#event_departments',
                                  as: :admin_event_departments

  get '/about',   to: 'pages#about',   as: :pages_about
  get '/terms',   to: 'pages#terms',   as: :pages_terms
  get '/privacy', to: 'pages#privacy', as: :pages_privacy
  get '/sitemap.xml', to: 'pages#sitemap', as: :pages_sitemap

  get '/:username', to: 'profiles#home', as: :profile_home
  get '/venues/:id/:slug', to: 'venues#show', as: :venues_show
  get '/events/:id/:slug', to: 'events#show', as: :events_home
end
# rubocop:enable Metrics/BlockLength

app/models/event_types/mixins.rb
module EventTypes
  module Mixins
    def delete
      return false if events.any?
      self.deleted_at = Time.zone.now
      save!
    end

    def undelete
      self.deleted_at = nil
      save!
    end
  end
end

app/controllers/event_types/create.rb
module EventTypes
  class Create < ::AdminControllerAction
    def call
      event_type
      redirect
    end

    private

    def redirect
      redirect_to(
        controller.admin_event_types_path,
        notice: 'Event type added'
      )
    end

    def safe_params
      @safe_params ||= params.require('event_type').permit(
        :name, :description, :event_department_id
      )
    end

    def event_type
      @event_type ||= ::EventTypes::Creator.new(safe_params, current_user).call
    end
  end
end

app/controllers/event_types/destroy.rb
module EventTypes
  class Destroy < ::AdminControllerAction
    def call
      message = event_type.delete ? 'event type deleted' : 'Cannot delete that'
      redirect message
    end

    private

    def redirect(message)
      redirect_to(
        controller.admin_event_types_path,
        notice: message
      )
    end

    def event_type
      @event_type ||= EventType.find params[:id]
    end
  end
end

app/controllers/event_types/edit.rb
module EventTypes
  class Edit < ::AdminControllerAction
    def call
      expose(event_type, '@event_type')
      expose(existing_event_types, '@existing_event_types')
    end

    private

    def event_type
      @event_type ||= EventType.find params[:id]
    end

    def existing_event_types
      @existing_event_types ||= EventType.order(:name)
    end
  end
end

app/controllers/event_types/new.rb
module EventTypes
  class New < ::AdminControllerAction
    def call
      expose(event_type, '@event_type')
      expose(department, '@department')
    end

    private

    def event_type
      @event_type ||= EventType.new event_department_id: department.id
    end

    def department
      @department ||= EventDepartment.find params[:event_department_id]
    end
  end
end

app/controllers/event_types/update.rb
module EventTypes
  class Update < ::AdminControllerAction
    def call
      logger.call if event_type.update safe_params
      redirect
    end

    private

    def redirect
      redirect_to(
        controller.admin_event_types_path,
        notice: 'The event type has been updated'
      )
    end

    def safe_params
      @safe_params ||= params.require('event_type').permit(
        :name, :description, :event_department_id
      )
    end

    def event_type
      @event_type ||= EventType.find params.fetch(:id)
    end

    def logger
      @logger ||= ::Utilities::Logger.new(event_type, 'edited', current_user)
    end
  end
end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  def edit
    ::EventTypes::Edit.new(
      self, params
    ).call
  end

  def new
    ::EventTypes::New.new(
      self, params
    ).call
  end

  def create
    ::EventTypes::Create.new(
      self, params
    ).call
  end

  def update
    ::EventTypes::Update.new(
      self, params
    ).call
  end

  def destroy
    ::EventTypes::Destroy.new(
      self, params
    ).call
  end
end

app/views/event_types/edit.html.haml
- present @event_type do |event_type|
  - content_for :page_title do
    = event_type.name
    Edit

  = simple_form_for(@event_type, url: event_type_path, method: :put) do |f|
    .panel
      .panel-head
        Edit event type
      .panel-body
        .row
          = f.input :name, as: :string, label: 'Name', placeholder: 'Give it a name'
        .row
          = f.input :description, label: 'Keywords'
        .row
          = f.association :event_department, label: 'Department'
        .row
          = f.submit 'Save'

  .panel
    .panel-head
      = "Existing Event Types (#{@existing_event_types.count})"
    .panel-body
      - @existing_event_types.each do |type|
        - next if type.id == event_type.id
        .row
          = type.title
          .pull-right
            = type.events.count
            events
  = render 'logs/log_list', logs: event_type.logs

app/views/event_types/new.html.haml
- present @event_type do |event_type|
  - content_for :page_title do
    New event type

  = simple_form_for(@event_type, url: event_types_path, method: :post) do |f|
    = f.input :event_department_id, as: :hidden
    .panel
      .panel-head
        Add event type
      .panel-body
        .message
          You're adding a new event type. Users select one of these when adding
          a new event.
        .row
          = f.input :name, as: :string, label: 'Name', placeholder: 'Give it a name'
        .row
          = f.submit 'Add event type'

  .panel
    .panel-head
      = "Existing Event Types (#{@department.event_types.count})"
    .panel-body
      - @department.event_types.each do |event_type|
        .row
          = event_type.title
          .pull-right
            = event_type.events.count
            events